[package]
name = "zuri"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "1.5", features = ["api-all"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
name = "zuri"
path = "src-rust/lib.rs"
